### ISSUE TITLE
Guidelines for contributors

### ISSUE THREAD

**Issue by andylolz** [okfn/okfn.github.com#130]
I’m increasingly aware that I am very inconsistent with my OKF labs contribution workflow, and some of my practices are possibly quite bad!

Do guidelines exist for this? If not, perhaps there could be a set of general OKF labs guidelines that individual projects override as required. Does that seem ok, or a bit prescriptive?

As a starting point for a guideline doc, **here are the subjectively good bits I’ve been following:**

 * _Most of the time_, I create a pull request, [referencing/closing the issue from the pull request](https://github.com/blog/1506-closing-issues-via-pull-requests). If a github issue doesn’t already exist, I create one (again – most of the time!)
 * I always branch from master
 * I merge from master to keep my PR branch up-to-date and auto-mergeable
 * I don’t merge my own PRs

**Here are the specific / neutral bits:**

 * I name my branches with the following convention: `[issue number]-[v brief summary]`
 * If I expect someone else may want to contribute to a branch, I push to the okfn remote. Otherwise, I push to my clone (just because it seems tidier).

Ok \*gulp\*… **here are the bad bits:**

 * If it’s a small tweak (e.g. a typo) I push direct to master and don’t PR
 * I often PR and then continue committing
 * I usually reference issues from commits, too, which creates a bit of clutter in issues
 * I sometimes force push branches on my clone in order to remove bad commits
 * My PRs often don’t have associated tests / docs

**Comment by rgrp** [comment]
FIXED. https://github.com/okfn/coding-standards now exists.
