### ISSUE TITLE
Establish informal sysadmin team

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#142]
Please add a comment with your name below if you are interested!

How it will work:

* We'll probably establish a rota.
* Need to be "contactable" (on irc) during "normal" hours - e.g. day your time, when on rota (probably one week a month or less depending on numbers involved). We don't run a lot of mission critical stuff here so its pretty informal.
* 1-3h per month of time to dedicate (either during rota or otherwise)

Responsible for [Labs Resources](http://okfnlabs.org/about/resources/) especially:

* Oversight and access to our dedicated servers
* Granting access (e.g. to repos, storage etc)

How to sign up: express your interest by adding a comment ...

**Comment by rgrp** [comment]
@mchelen @danfowler I propose we designate you two plus myself as the current official sysadmins :-) (we need to get ourselves badges ;-) ...)

Next steps will be getting credentials - cf #223 and then making sure you have access to labs machines.

**Comment by danfowler** [comment]
:neckbeard:

**Comment by mchelen** [comment]
Sounds good, one thing to think about is where issues will be aggregated, so we know when someone needs help.

**Comment by rgrp** [comment]
@mchelen great question - what do you think of using this issue tracker and if that gets messy we can boot a dedicated one (definitely think we want a proper tracker not e.g. the [discussion forum](http://discuss.okfn.org/) - if things arise there and become an actual request they can become an issue here)

**Comment by rgrp** [comment]
@danfowler you have the most awesome emoticons ;-)

**Comment by rgrp** [comment]
@danfowler would you be happy to take a lead on #223

**Comment by mchelen** [comment]
@rgrp Using this issue tracker sounds good, just need to add a section in http://okfnlabs.org/contact/ to let users know.

**Comment by danfowler** [comment]
@rgrp yup! and you can thank :octocat: for the emoticons!

**Comment by rgrp** [comment]
So what we need to do, to close out:

* [ ] #223 (sysadmin info recorded)
* [ ] add info to contact page about getting hold of sysadmins on contact page - @mchelen do you have a suggestion here
* [ ] add Labs Sysadmin as a role and add this to relevant folks so it shows up on badges page

Anything else?

**Comment by rgrp** [comment]
@mchelen @danfowler are you happy to take this forward? I think we are close to being able to close.

**Comment by danfowler** [comment]
Having added the contact info, moving to close.
