### ISSUE TITLE
Project filters should be reflected in the URL of the project listing

### ISSUE THREAD

**Issue by stefanw** [okfn/okfn.github.com#198]

**Comment by danfowler** [comment]
@stefanw was this what you were thinking almost exactly this time last year?
![screen shot 2015-03-12 at 10 18 06 am](https://cloud.githubusercontent.com/assets/772616/6613656/3fe74aac-c8a1-11e4-9d49-f0336c7002a3.png)

**Comment by stefanw** [comment]
I guess so, can't exactly remember. But looks sweet!

**Comment by danfowler** [comment]
wdyt @loleg @andylolz @mchelen ?

**Comment by rgrp** [comment]
I think its great :-)

**Comment by danfowler** [comment]
great :)

**Comment by loleg** [comment]
+1. À la hash tags, e.g. #perl

**Comment by loleg** [comment]
Never mind saw they already are displayed in project detail. Permalinks to listings by type are a good thing so yes.

**Comment by danfowler** [comment]
Cool.  Will merge.

**Comment by danfowler** [comment]
For example: a link to projects where help is wanted and one of the languages used in Javascript: http://okfnlabs.org/projects/#helpwanted=true&language=javascript
