### ISSUE TITLE
Update site branding

### ISSUE THREAD

**Issue by nmashton** [okfn/okfn.github.com#217]
As David Read pointed out, the Labs website is still using the old branding: it refers to Open Knowledge as "Open Knowledge Foundation", uses the old logo, etc. (Actually, he just pointed out that the newsletter was sent out under the old name... but this highlights a broader problem.)

Fixing this will involve a bunch of tasks:

- [x] site logo
- [x] color scheme
- [x] Twitter avatar
- [x] all textual references to "Open Knowledge Foundation" on the site

Are there any I've missed?

**Comment by danfowler** [comment]
There are still a bunch of references to Open Knowledge Foundation in, say, _layouts/default.html and the Open Graph Protocol stuff in <head> (for Facebook sharing) links to the old logo.

**Comment by rgrp** [comment]
@danfowler great point - would you be up for doing s/Open Knowledge Foundation/Open Knowledge/g?

**Comment by danfowler** [comment]
Sure

**Comment by danfowler** [comment]
The favicon located at "http://assets.okfn.org/p/okfn/img/favicon.ico" needs to change.  Twitter avatar should probably be: "http://assets.okfn.org/p/labs/img/icon-512.png".

**Comment by rgrp** [comment]
@danfowler as a sysadmin I suggest you get access to okfnlabs twitter both to tweet and then can also update the icon.

**Comment by danfowler** [comment]
cool, icon updated, will fix the Twitter color scheme to match @okfn probably

**Comment by rgrp** [comment]
@danfowler anything remaining here before we close?

**Comment by danfowler** [comment]
I would propose a few more that I'm looking at:

- [ ] upload new version of favicon to s3 (I've made a version that I can upload when I have access)
- [ ] change default font-face to "Lato" (...and make the relevant additional adjustments)

**Comment by rgrp** [comment]
@danfowler on font-face we can leave for the moment and fix later

re s3 can you push / pull request to https://bitbucket.org/okfn/assets.okfn.org

**Comment by danfowler** [comment]
artist's rendering of new color scheme + lato font - grid background (which I think clashes a bit with the new color scheme)
![screen shot 2015-02-13 at 6 56 53 pm](https://cloud.githubusercontent.com/assets/772616/6191442/32851712-b3b2-11e4-9f2f-c3915828161a.png)

**Comment by danfowler** [comment]
OK.  Merged in very simple search-and-replace-level color scheme changes + use okfn.org's favicon. A Labs-specific favicon & Lato can come later (if at all).  I guess the question is how closely Labs should hew to the greater Open Knowledge brand.

**Comment by danfowler** [comment]
Closing as the current site branding now seems fully aligned with Open Knowledge brand w/r/t logos, colors, etc.
