### ISSUE TITLE
Record Labs sysadmin info somewhere

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#223]
Suggest using `sysadmin` folder in this repo (or possibly /about/sysadmin/)

Suggest storing:

* List of Labs sysadmins (+ their public keys??)
* List of services we run and their mapping to machines
  * A service can be a webapp or just a DB (where DB is service in itself)

Suggest storing as either json or csv ...

cf how we used to do things in the main sysadmin/infra repo for OK International: https://github.com/okfn/infra/blob/16fee4cd0b9e0723d24418d5bccf82ed1f649692/ssh_keys.js

**Comment by rgrp** [comment]
@danfowler we can have a simple json or csv file here - all we need is name and ssh key at the moment i think :-)

**Comment by danfowler** [comment]
cool, sounds simple enough

**Comment by danfowler** [comment]
@rgrp I put something together.  Was this what you were thinking?

**Comment by rgrp** [comment]
Yes, though I, personally, prefer csv or json to yaml ;-0

Let's get this up. And then we ping ok sysadmins re getting your keys on relevant machines.

**Comment by rgrp** [comment]
@danfowler are you happy to merge in?

**Comment by rgrp** [comment]
@danfowler can we get this merged in :-)

**Comment by danfowler** [comment]
Sorry, I missed this. Been traveling for the last week and for the next two weeks. Merging what I have.

**Comment by danfowler** [comment]
OK, thanks to @mattrm I have access to the servers, and I added some actual info into the machines.yml file.  CSV output available as machines.csv and sysadmins.csv in the /about/sysadmin/ folder.  Couldn't think of a way to write correct json directly.

**Comment by rgrp** [comment]
@danfowler great work here. Do you think we can close as FIXED?

**Comment by danfowler** [comment]
Yes. FIXED.
