### ISSUE TITLE
Labs "roles" attribute on person profile shown on their page

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#255]
Proposal: introduce a roles attribute on a person to list their role(s). Would also like to display this with a nice appropriate badge on the members list and their personal page ...

Roles
* sysadmin
* lead
* webministrator
* (Blog) editor
* (Newsletter) editor

Other recognition
* Attended an open data maker night
* Run an open data maker night
* Written a blog post
* Contributed to the newsletter

## Status field

Originally issue #84 

Status field is one of:

- member
- contributor (=> official contributor)
- lead
- alumni

This is used in some way on the members page to indicate people's status :-)

**Comment by rgrp** [comment]
@danfowler / @mchelen I think we also should show these badges (perhaps in smaller size on the members page). wdyt?

I also wonder if we should colour code the badges a bit to distinguish types of badges. e.g. "roles" style badge like lead or sysadmin might be orange whilst awards (e.g. ran open data maker night is green). wdyt?

**Comment by danfowler** [comment]
Agreed on both counts. There should be some distinction between having an ongoing role and being recognized for a one-time contribution.

**Comment by danfowler** [comment]
![screen shot 2015-01-05 at 4 34 08 pm](https://cloud.githubusercontent.com/assets/772616/5613741/0352ff76-94fa-11e4-846c-f562b72a2e0f.png)

Colors are nice.

**Comment by rgrp** [comment]
@danfowler looks lovely.

**Comment by rgrp** [comment]
FIXED :-)
