### ISSUE TITLE
[project] Add BibServer project page

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#270]
https://github.com/okfn/bibserver

BTW: bibserver, facetview and bibjson all go together - wonder if we need some way to indicate "linked to" style relationship for projects ...

**Comment by rgrp** [comment]
@danfowler up for this one too?

**Comment by danfowler** [comment]
![bibserver](https://cloud.githubusercontent.com/assets/772616/5678298/dce3743c-9801-11e4-8486-7714c87e814c.png)

**Comment by danfowler** [comment]
I linked to the related projects in the description.
