### ISSUE TITLE
Individual project page includes activity stream from github (if github based)

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#272]
Similar to activity stream on http://okfnlabs.org/ideas/ (and can use githubActivity.js -https://github.com/okfn/githubActivity.js)

Should show latest 5-10 activities for this project (perhaps in sidebar or next to description).

**Comment by danfowler** [comment]
This will make it easier to hit the GitHub API request limit (though probably only for very enthusiastic project browsers).

**Comment by danfowler** [comment]
Looks good when populated, but probably needs a better empty state.

![screen shot 2015-01-12 at 11 16 05 am](https://cloud.githubusercontent.com/assets/772616/5720178/d6b802de-9b31-11e4-955b-36b0408b7d7e.png)
![screen shot 2015-01-13 at 2 36 18 pm](https://cloud.githubusercontent.com/assets/772616/5720179/d6bac226-9b31-11e4-84d0-72b6163ed50e.png)

**Comment by danfowler** [comment]
Feature added, closing.

**Comment by rgrp** [comment]
w00t!
