### ISSUE TITLE
Determine status categories for projects and apply them consistently

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#274]
Projects have some kind of life-cyle. E.g. here's a rough stab:

* Starting
* Alpha
* Beta
* Stable
* Complete and/or Ongoing
* Retired / Archived

### Why do we care?

As a New Visitor who is interested in contributing to projects I want to know what state projects are in so that I can know where to contribute

As a Browsing Visitor (not planning to contribute) I want to know whether a project is just starting, mature or complete (and maybe archived) so that I can work out whether a project is active or finished or ... (helps me evaluate)

**Comment by danfowler** [comment]
Mentioning #294 here to link the two issues.

As a New/Browsing Visitor, is it worth distinguishing too finely (e.g. "Starting", "Alpha", and "Beta")?  Should a periodic "project census" be scheduled to get a sense of each project's status?

**Comment by danfowler** [comment]
In light of product-open-data: "Rebooting"?

**Comment by rgrp** [comment]
@danfowler I'm not sure about rebooting but it does make me think that maybe we improve helpwanted category to have e.g. "Maintainer Wanted", "Contributor Wanted" etc - i.e. clearer when something is missing an owner.

**Comment by danfowler** [comment]
@rgrp perhaps "Maintainer Wanted" and "Contributor Wanted" could fall under the typeofhelp attribute and we could provide those as suggestions in the project add page or a nice new prose.io GUI

**Comment by rgrp** [comment]
+1 to that suggestion @danfowler

**Comment by davbre** [comment]
@danfowler is the idea to add a single attribute to each project page or add multiple attributes? I notice that in some projects a "status" attribute has been set, e.g. [activityapi](https://github.com/okfn/okfn.github.com/blob/master/projects/_posts/1970-01-01-activityapi.html). In other projects there are "helpwanted" and "typeofhelp" attributes, e.g. [For your information](https://github.com/okfn/okfn.github.com/blob/master/projects/_posts/1970-02-14-fyi-org-nz.html).

If we're going with say the "status" attribute, based on what information are we going to assign a status (e.g. make a judgement based on github activity, direct contact with project owner etc)?

**Comment by todrobbins** [comment]
This isn't necessarily analogous to our work, but both GDS (UK) and 18F (US) have service design phases that are worth checking out:

* https://www.gov.uk/service-manual/phases
* https://18f.gsa.gov/dashboard/stages/

I think it'd be good to model ours after these emerging best practices.

**Comment by rgrp** [comment]
Let's move this forward! @davbre great points. The more I think about it the more i think there are probably two state / status categories:

* Maturity status: Bleeding-edge, Alpha, Beta, Stable, Super-Stable etc
  * Or for a bit less codey ;-): "infant, teenager, adult, mature, retired, finished/complete
* Activity status: booting-up, active, dormant, retired/archived

I can imagine having projects at different points in these two e.g. a stable project that is now dormant or a very active project that is an "infant".

What do people think? I think it would also be worth doing a script to extract all the current projects with their metadata to a spreadsheet (or do this via jekyll)

**Comment by davbre** [comment]
Regarding two status categories, I don't mind. The current status category can take multiple values as its values are stored in an array. Maybe one category could cover what you suggest?

In any case, I've written a script to read the project metadata and put it into a csv file. Here's the [script](https://github.com/davbre/scripts-misc/blob/master/okfnlabs-issue274-projects-to-csv.rb) and the [output](https://github.com/davbre/scripts-misc/blob/master/output/okfnlabs-projects-metadata.csv).

One option here would be to take a copy of the csv file and update it with whatever status values you like, adding additional status columns if they're required. Once done, we could use another script to update the project files. Let me know what you think.

**Comment by rgrp** [comment]
@davbre ok let's try two categories.

Re the CSV - that's great! I was even thinking we could do this automatically in jekyll -- see e.g. http://idratherbewriting.com/2015/03/06/pushing-content-into-any-format-with-jekyll/ -- and then have it available at http://okfnlabs.org/projects.csv or http://okfnlabs.org/projects/all.csv. wdyt? If you were up hacking that in would welcome the pull request :-)

**Comment by davbre** [comment]
@rgrp reading from a csv file sounds good to me. See the PR I just made.

Regarding reading from a google spreadsheet, I did a quick search. We could use the [tabletop](https://github.com/jsoma/tabletop) js library along the lines of the following [stackoverflow question/answer](http://stackoverflow.com/a/27424053/1002140). What do you think....any other ideas?

**Comment by rgrp** [comment]
@davbre sorry for confusion but what i meant was:

Use jekyll frontmatter on each project page to generate a csv file called `/projects.csv/` or `/projects/all.csv`.

This would be useful to have going forwards generally **and** we would then use this CSV to load into google spreadsheet to allow us to look through easily and do reclassification. We would then discard this google spreadsheet once done and apply any relevant changes by hand.

The point is that we probably want to keep the source of truth for projects and their metadata being the project page in the jekyll system so it is easy to edit and manage on a per project basis.

Does this make sense?

**Comment by rgrp** [comment]
Thanks to @davbre efforts this is now live at http://okfnlabs.org/projects/all.csv.

I've now extracted this into a google spreadsheet here which we can use for working through recategorising quickly and easily in one place:

https://docs.google.com/spreadsheets/d/1CiVqAeKqj_U57bDBW1Jz95WN6dS39Rup-hvqvDj2idE/edit#gid=1632238835

@davbre (and @danfowler) the next step would be go through and categorise these - please jump in if you have a moment :-)

**Comment by rgrp** [comment]
@danfowler @davbre I've done a pretty complete run-through in the spreadsheet.

I think we should review and then once in agreement, start implementing some changes.

**Comment by davbre** [comment]
@rgrp Before implementing the changes you've made in the google spreadsheet by hand (or script), I think it's worth considering migrating most of the project metadata to a CSV file. Updates to the CSV file would automatically update the corresponding project pages. It would mean changes could very easily be made in bulk. Adding/removing project attributes would be the same (just add a column to the CSV file). To satisfy my own curiosity I had a go at implementing this on my own [fork](https://github.com/davbre/okfn.github.com/tree/projects-from-csv). The main things to note on this fork are that each project's page contains very little metadata, as most of it lives in the ../_data/projects.csv file. What do you reckon? We ca discuss further, on the gitter channel if you like.

**Comment by rgrp** [comment]
@davbre this definitely sounds promising and being able to edit bulk in one place is nice. I guess the question how much in the main CSV vs in the page. My sense is we want to keep stuff that a project owner would edit in the jekyll metadata and move rest to the CSV (stuff for site editors and curators)

As a rough stab:

- In page: title, author, contributors, project_url, github_url, imageurl
  - get rid of `slug` and `permalink` if we can
- In CSV: activity, maturity, priority, type, language

**Right now the main thing is just to move this forward so I'm pretty happy with any option that allows us to get moving including just having everything in CSV for the moment.**

Aside (and for separate issue):

* We probably want to move projects out of being listed in _posts (which is hacky) and just list them as `/projects/{project-slug}/index.md`
* We can set `layout` and fact these are `project` section in the _config.yml using the subselector syntax

**Comment by rgrp** [comment]
@davbre i'm actually thinking about this - let's get moving and i think easiest is the stuff all in the CSV so can you do a pull request based on your fork. One comment on that - it does look like multi-value items have got "mashed" into one long string in csv https://github.com/davbre/okfn.github.com/blob/projects-from-csv/_data/projects.csv e.g. see language or type column - can we fix this?

**Comment by rgrp** [comment]
@davbre great - i've merged the PR. First a big thank-you: looks awesome and much cleaner now!

Couple of quick questions on the PR:

* What's +/- of jekyll collections vs having the projects *inside* /projects/ and using _config.yml to bulk set properties? I'm guessing the main thing is the slug is nicely generated ...
* AFAICT we have *not* yet merged the changes from the google spreadsheet into the `_data/projects.csv` (which si great). If so, that's next step and we should plan that out quickly ... (and would you be up for implementing once changes are agreed).

I'm going to import the current `_data/projects.csv` into our google doc and comment.

**Comment by rgrp** [comment]
Next steps:
 
* Implement priority and make changes to featured
* Implement the `maturity_status / stage` and `activity_status`
  * Question: what category namings do we use: do we go for "geeky" or the more non-tech `infant, teenager, etc` - thoughts wanted @davbre @danfowler 

Other

* On projects add page add the enumerations we have created and their explanations
* Define priority and similar

General comments - In spreadsheet i've put comments on second line and copied a few here ...

* `author / maintainers / contributors`: we have too many options. I think we want to simplify. Probably a separate issue.
  * `author` should also be a labs username and is probably better called `owner` (??)
* Delete `tags`
* `permalink` and `slug`: can we delete now?

**Comment by davbre** [comment]
@rgrp - yes, I can take up making various changes.

Regarding collections...Having read some of the Jekyll documentation, they seemed a natural fit...

- It allows you to refer to site.projects in the liquid templates (so no pre-filtering is required)
- it gives you a nice url using the filename
- no date is required in the filename (as with posts)
- with posts you have the date in the filename, which in turn determines the ordering of the posts when iterating over them. However, with our metadata in the CSV file we can control this by ordering as we want. I had already included a "sort_order" column, which is just there for convenience
- with posts, we were previously overwriting the default permalink using the "permalink" attribute. This is no longer needed. In fact, I have already removed it from the CSV file (the "slug" attribute has also been removed).


Regarding the "activity_status" and "maturity_status"  changes, you're correct - I didn't update those (I thought I had :)) I'll update those shortly and will submit a pull request.


"maturity_status" vs "stage". Are you suggesting we use one and drop the other? I'm not a fan of the use of "infant", "teenager", "adult", but _don't_ feel strongly about it. I would prefer something like  "new", "developing" and "mature" instead.


The spreadsheet - you say you put comments on the second line. I don't see what you mean...Are you referring to the google docs spreadsheet? Can you clarify?

**Comment by rgrp** [comment]
@davbre 

* do we use `stage` or `maturity_status`? They are, I think, the same thing.
* I agree re "infant" etc. I've switched to new naming. Can we update `maturity_status / stage`
* Re spreadsheet i did mean google docs spreadsheet - that's what I'm updating and which we should then sync in relevant ways with main sheet.

**Comment by rgrp** [comment]
@davbre i'm also splitting stuff not related to `priority, maturity_status, activity_status` into a separate issue at #424

**Comment by davbre** [comment]
@rgrp - my latest merge request includes
- `stage` and `maturity_status` are merged into `stage`
- I've applied the new values to `stage` (i.e. dropped "infant", "teenager" etc, in favour of "developing", "mature" etc)
- for the moment let's standardize on true/false as that's what the site already uses. I can update that at a later stage, if necessary

**Comment by danfowler** [comment]
@rgrp @davbre this looks like really great and useful work.  Allow me to take a close look at this tomorrow :mag:

**Comment by rgrp** [comment]
@danfowler on this we are now ok - we've made the relevant decisions so you can ignore this one as we have it "under control".

**Comment by danfowler** [comment]
Marked as done in #405 so closing.
