### ISSUE TITLE
New Badges Round 1

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#278]
Wanted to brainstorm additional badges:

Roles:

- Project Contributor - contribute to one or more of the Labs projects (i.e. on projects page)
 - Project Lead (?) - atm i don't think we distinguish

Achievement

- Website fix - you have submitted at least one pull request to improve the website
- Forum / mailing list post (?)

----

Asides:

- Want to document how people can claim / apply badges (e.g. submit a pull request with X change to your profile)

**Comment by rgrp** [comment]
@danfowler @mchelen ^^^ - also should we ping the mailing list about this (perhaps first tell them about aweseome badging work we have implemented!)

**Comment by danfowler** [comment]
Pulling a bit from @mchelen [suggestions](https://github.com/okfn/okfn.github.com/issues/255#issuecomment-67101527):

Project Maintainer ("Lead"): http://fontawesome.io/3.2.1/icon/star/
Project Contributor: http://fontawesome.io/3.2.1/icon/star-empty/
Website fix: http://fontawesome.io/3.2.1/icon/wrench/
Forum / mailing list post: http://fontawesome.io/3.2.1/icon/comment/ 
(though not sure this one is worth being elevated to "achievement" status)

Alternatively:
Project Maintainer ("Lead"): http://fontawesome.io/3.2.1/icon/flag/
Project Contributor: http://fontawesome.io/3.2.1/icon/flag-alt/

**Comment by rgrp** [comment]
The more I think the more I'm +1 on distinguishing lead from contributor.

Re lead icon: I think we could use the current rocket ship (we use for labs lead) and have labs lead have the "key" icon ("keys to the kingdom" thing). I'm -1 on flag as not very clear and I think we should reserve stars for use in "starring" (I'm actually wondering if all achievements are of form "star" + something ...)

**Comment by rgrp** [comment]
@danfowler would you be up for emailing the labs list about this thread and soliciting input - i think this is a good issue for people to opine on :-)

**Comment by danfowler** [comment]
Yeah, I'll put an :email: together.

**Comment by mchelen** [comment]
I like "key" for labs admin, "rocket" for project maintainer, and the idea of distinguishing between project maintainer & project contributor. The only thing I'm not sure about is what icon to use for project contributor? Here are some options, maybe one would be good:
http://fontawesome.io/3.2.1/icon/briefcase
http://fontawesome.io/3.2.1/icon/cloud-upload
http://fontawesome.io/3.2.1/icon/cogs
http://fontawesome.io/3.2.1/icon/keyboard
http://fontawesome.io/3.2.1/icon/lightbulb
http://fontawesome.io/3.2.1/icon/puzzle-piece
http://fontawesome.io/3.2.1/icon/code-fork

**Comment by rgrp** [comment]
@mchelen @danfowler next steps here? Let's get a summary proposal, review and then action ...

**Comment by danfowler** [comment]
1. [ ] generate PR based on these suggestions (I'm thinking "cog" for contributor, "comment" for forum commenter, and "code-fork" for website fixer.)
1. [ ] review and merge PR
1. [ ] brainstorm next steps to feed into new issue
    1. remove potentially redundant roles ("webmin")?
    1. thinking about workflow/interface for issuing/requesting a badge?
    1. think about what might make people *want* to earn a badge?

**Comment by todrobbins** [comment]
Have we already gathered use cases of other badge issuers? If not, I can work on a comparison of the varying issuers (School of Data, https://badges.webmaker.org/, etc.).

**Comment by rgrp** [comment]
@todrobbins that would be great.

**Comment by danfowler** [comment]
:+1:

**Comment by todrobbins** [comment]
Cool. I'll start my work on it.

**Comment by danfowler** [comment]
For the next round: Data Curator and Managing Data Curator badges

**Comment by schlos** [comment]
+1

**Comment by rgrp** [comment]
+1

**Comment by rgrp** [comment]
@danfowler can we close this and open an issue for remaining items?

**Comment by danfowler** [comment]
Yes.

**Comment by rgrp** [comment]
@danfowler can you link the new issue for remaing itesm - really useful for people who read to end of here.
