### ISSUE TITLE
Projects List supports simple text search

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#282]
In addition to the filters it would be nice if you could do simple text search of titles.

i.e. if i type "public" i would get all projects whose titles match "public" (it would be nice if this matching happened live - i.e. on each keystroke the filter was applied ...)

**Comment by rgrp** [comment]
@danfowler @loleg @mchelen what do you think

**Comment by loleg** [comment]
Considering this can be done by browser find, plus that if people are looking for a specific project they are more likely to Google it, I would rather think about site-wide full text search?

**Comment by rgrp** [comment]
@loleg I'm a bit concerned re UX - i keep going there and typing and then realizing that doesn't work and i have to do Ctrl+F. Usually when I see a search box I think i can search (though I realize this one is a filter box - maybe we can signpost that better somehow).

**Comment by danfowler** [comment]
:+1:

**Comment by danfowler** [comment]
Looking at this again, an easy fix is to simply add a project's title to the drop-down list and filter on that (only, of course, yielding one result if selected).  Thanks to the nicely written projects.js, only a couple of very minor modifications were needed to get this in (see #301).

**Comment by danfowler** [comment]
Another benefit of this approach is that it searches tags and titles at the same time.  

![screen shot 2015-02-19 at 11 48 21 am](https://cloud.githubusercontent.com/assets/772616/6264520/61a0dd72-b82d-11e4-8c9d-781ee0556fe3.png)

Willing to merge in today as it's pretty simple.  Does anyone want to test?

**Comment by rgrp** [comment]
Go for it and merge - we can test on the site :-)
