### ISSUE TITLE
Achievements and Roles page

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#284]
I think it could be nice to have an Achievements and Roles page (either one page or 2 separate) where we list people by role and achievements (now that we have roles and achievements). Alternatively we could have one page called just "badges"

Suggest:

```
/about/roles/
/about/achievements/

or

/members/roles/
/members/achievements/

or

/members/badges/ # both roles and achievements
```

This might also be the better place to list the categories of roles and achievements than the current `/join/` page.

**Comment by rgrp** [comment]
@danfowler @mchelen @mattfullerton @markbrough @loleg  wdyt?

**Comment by loleg** [comment]
I think filter buttons on the Members page could work well too. Having a single badge page seems like the trendy thing to do these days, viz. [Webmaker](https://webmaker.org/en-US/badges/webmaker-super-mentor), and their detailed explanation of what the role/accomplishment entails. Speaking of which, are we already using/considering [OpenBadges](http://openbadges.org/)?

**Comment by rgrp** [comment]
@loleg we looked at Open Badges quite a bit here https://trello.com/c/LvcBmpiN/6-badges-okfn-org-giving-recognition-for-what-people-learn-and-do-around-the-network

Personally, I've struggled to grok exactly how to use openbadges to do simple stuff, quickly but I would be delighted to use it if it would deliver value and be relatively easy to use.

**Comment by danfowler** [comment]
I agree that a single `/members/badges/` page would be nice, and the `/join` badges stuff could be moved there.  @loleg this badging implementation falls under the category of "Jekyll tricks", though  I wonder if it would be possible/worth the effort to conform to the [assertion standard](https://github.com/openbadges/openbadges-specification/blob/master/Assertion/latest.md) for OpenBadges (hosted) badges by rigging Jekyll to output the relevant JSON files.

**Comment by rgrp** [comment]
@danfowler looking at http://okfnlabs.org/members/badges/ this is great but we do not yet have any listing of people under each badge - a key user story here is seeing who has which role (and perhaps on which project).

**Comment by danfowler** [comment]
Right.  I'll put this together.

**Comment by danfowler** [comment]
OK, with the last merge I think we have something here :smile:

**Comment by rgrp** [comment]
@danfowler one minor thing - people images on badges page link to url with index.html in it. any way to get to base url e.g. 

http://okfnlabs.org/members/mattfullerton/ vs http://okfnlabs.org/members/mattfullerton/index.html (we want the former)
