### ISSUE TITLE
Blog roll outdated links & current inspiration

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#287]
The "blogroll" on http://okfnlabs.org/blog/ has many broken/outdated links.  Some could be fixed, but I thought it might be worth creating a *new* list of "places we find inspiration".

**Comment by rgrp** [comment]
@danfowler right now i suggest we move the blogroll (if many broken links) and then re-add in a little bit once we have a good new list.

My sense also is I'd rank this as low priority on website vs other issues such as #284

**Comment by danfowler** [comment]
totes

**Comment by danfowler** [comment]
Some have pretty direct new homes, so I can just fix those up and remove the rest.

**Comment by rgrp** [comment]
+1

**Comment by danfowler** [comment]
Fixed.
