### ISSUE TITLE
Add "improve this page" link to the bottom of pages linking to relevant github page here

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#29]

**Comment by danfowler** [comment]
I think prose would be a great option in general, but even better for adding a project.  The appropriate additions to the _config.yml file can ease the creation of a project by providing an easy interface for adding common tags, etc.

**Comment by danfowler** [comment]
Not ready for PR yet, but here is a prose interface for adding a project: http://prose.io/#danfowler/okfn.github.com/new/improve-this-page/projects/_posts

**Comment by danfowler** [comment]
I think linking directly to the GitHub edit page is preferable at least for "Improve this page". Prose is a marginally nicer editing experience, but adds another layer between the editor and the edit he/she is trying to make. Plus, the user will have to authorize on GitHub before committing the edit anyway.
