### ISSUE TITLE
[Project] Reassign maintainer on oklabs site to dan fowler

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#290]
Propose: in recognition of @danfowler work and leadership here that he take over as "maintainer" ("lead") on http://okfnlabs.org/projects/open-knowledge-labs-website/

PS: should we rename "maintainer" to "lead" or something like that in the template?

**Comment by danfowler** [comment]
Thanks! I definitely accept. I don't personally see a pressing need to change maintainer to lead especially when the site has other "leads".

**Comment by rgrp** [comment]
@danfowler sounds good.
