### ISSUE TITLE
Add new project status: "graduated"

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#294]
Propose new project status: "graduated" which means the projects has successfully graduated (usually on to pastures new).

We would apply this to e.g.

- Crowdcrafting
- Annotator 
- Kartograph

**Comment by rgrp** [comment]
@danfowler wdyt?

**Comment by danfowler** [comment]
Sounds good, I've been thinking of a way to display status to the user (possibly with an increasing bar or notch ending in :mortar_board:)

**Comment by rgrp** [comment]
oooh - love the icon!

**Comment by danfowler** [comment]
Yeah, it's neat.  Just need to upgrade to the latest font-awesome to support.  Might be good to transition to Bootstrap 3 in the process as well.
