### ISSUE TITLE
[Project] Add DataPortals.org as a project

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#295]
http://dataportals.org/ + https://github.com/okfn/dataportals.org/

@mattfullerton are you up for adding this one? Also I'd imagine you and I would be down as maintainers :-)

**Comment by rgrp** [comment]
@mattfullerton ping :-)

Instructions on: http://okfnlabs.org/projects/add/ (it will take <= 5m)

**Comment by mattfullerton** [comment]
Done
http://okfnlabs.org/projects/dataportals/

**Comment by rgrp** [comment]
@mattfullerton i would also suggest having you down as the maintainer (or at least you and I). wdyt - all you need to do is add your userid to the maintainer field on that project.

**Comment by mattfullerton** [comment]
Yes! I copied an existing project and that one had no maintainers so I forgot. Done now. Are we talking code maintainers here or site maintainers as well (I'm thinking of @schlos).

**Comment by rgrp** [comment]
I think we can include site maintainers for sure and would love to include @schlos if he wanted to be listed

**Comment by danfowler** [comment]
Adding screenshot...

![dataportals](https://cloud.githubusercontent.com/assets/772616/6437513/ffd4c264-c0d0-11e4-8cc2-f70b7a88444e.png)

**Comment by schlos** [comment]
:+1:

**Comment by mattfullerton** [comment]
@schlos - are you already listed as a member on the site?

**Comment by schlos** [comment]
hi @mattfullerton
Sorry for late reply. I missed somehow this.
No, I'm not yet listed as a member. What is the process?

**Comment by danfowler** [comment]
hi @schlos you can add a new file to the [members/_posts directory](https://github.com/okfn/okfn.github.com/new/master/members/_posts) of the site following the template and naming scheme listed [here](http://okfnlabs.org/members/signup/).  Looking forward to merging!
