### ISSUE TITLE
Make mysqldump data available for product-code

### ISSUE THREAD

**Issue by swmerrill** [okfn/okfn.github.com#296]
Before we can continue work on getting the product-open-data site back up we need access to the data which is presumably in a mysqldump file. Can we get that put somewhere that we can access it?

**Comment by rgrp** [comment]
@danfowler can I sync with you as Labs sysadmin to help move this forward. Ping me here and we can sort this.

**Comment by danfowler** [comment]
Cool, yes.  What can I do?  Just to let you know, I'll be a bit slower to respond over the next two weeks as I'm traveling.

**Comment by rgrp** [comment]
@danfowler ok so

1. we should ask @nigelbabu / @mattrm to get your ssh-key on the product-open-data.com current server (probably email sysadmin@okfn.org for this) (this is a labs server i believe)
2. Have a poke around to see where product-open-data.com is living
3. Either get a dump for @swmerrill  or invite @swmerrill to get his ssh key on there and fix directly!

**Comment by danfowler** [comment]
Cool. Doing.

**Comment by danfowler** [comment]
@swmerrill Here's the requested dump of product-open-data SQL: http://dfowler.sixbit.org/products.sql.gz

Excited to see this move forward!  Let me know what else you need.

**Comment by swmerrill** [comment]
I downloaded the products.sql.gz file and tried to extract it.

However, tar gives me the message "This does not look like a tar file."

The file is in binary. But it is not in tar, zip or bzip2 format.

Any idea what format it is in?

Thanks.
Stan

**Comment by danfowler** [comment]
Hi Stan,

This file is just gzipped (as opposed to tarred and gzipped), so gunzip
alone should work to decompress.

Cheers,

Dan

**Comment by swmerrill** [comment]
Thanks, Daniel. That worked fine. I gunzipped the file and read it into mysql with no problems. Once I got the site working, though, I found that there seems to be quite a bit of code missing from the github archive I downloaded. Do you know whether there is another archive?

**Comment by danfowler** [comment]
Here is a much larger (3GB) archive of the site: http://dfowler.sixbit.org/product-open-data.com.tar.gz 

Not sure about the exact contents, but this *is* tarred and gzipped, so the usual tar xzf will work.

**Comment by mattrm** [comment]
product-open-data.com is the code, or more accurately a dump of the /var/www folder from the server that product-open-data was on.  product.sql is the SQL dump of the database.

Just to be clear, that's all we have.  The code doesn't seem to be version controlled and there are no docs accompanying it.  The sysadmin who setup the website has left OK.  The chap who wrote the code hasn't been able to provide us with any information about it.  We have a dump of code and a database, that's it.  The server which product-open-data had been installed on has been deleted, as it was old and due for decommissioning (it was during the decommissioning that we found the code and db on the server).

I suspect that the best thing would be to extract the data from the database and then write a totally new app (documented and version controlled please) to view it.

**Comment by rgrp** [comment]
@mattrm i have some knowledge here so can help. We knew the core code was not version controlled though quite a bit of the other code is (see "product-*" repos under okfn).

Right now we are just looking to see if we can fix a minor bug and get the current site back up (it ran happily for 1y+). Next, we can get into the rewrite (which I think was what the django app was)

**Comment by danfowler** [comment]
OK, site is back up. I will see if I can commit the code at time of shutdown to the [original repo](https://github.com/okfn/product-browser-web).  Perhaps further discussion on immediate fixes and full rewrites can take place there?
