### ISSUE TITLE
GoodTables - do we want two separate projects listed?

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#319]
I wonder whether we want to have just one project listed on labs for goodtables covering both the lib and the web service.

/cc @danfowler @pwalsh

**Comment by pwalsh** [comment]
Yes you are right: there should only be one. I'll fix it tomorrow.

**Comment by pwalsh** [comment]
https://github.com/okfn/okfn.github.com/pull/321#

**Comment by danfowler** [comment]
Done.
