### ISSUE TITLE
Labs Hangout 2015 No 1 

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#320]
Someone just tweeted that they are looking forward to our next hangout and we have not had one yet in 2015: https://twitter.com/mehdisadeghii/status/578593730397077504

The structure is very simple and it can be anything from 30m to 1h: http://okfnlabs.org/events/hangouts/ (plus see previous tickets)

Who would be up for hosting / chairing the next one?

@loleg @danfowler @davidmiller @nickstenning @markbrough @mchelen @teleyinex @...

### Steps

* [x] Pick a date / time
* [x] put outline info in the etherpad: http://pad.okfn.org/p/labs-hangouts
* [x] add to events hangouts page - http://okfnlabs.org/events/hangouts/ (we need to automate!) - this is the page we link to in tweets etc
* [ ] ping labs list and ask people to add topics to etherpad etc (use model of @markbrough mail last time)
  * link to etherpad and http://okfnlabs.org/events/hangouts/ 
* [ ] tweet this out from okfnlabs account (suggest we link to http://okfnlabs.org/events/hangouts/)

Re booting of hangout: you can boot hangout on the day or @rgrp can (@rgrp advantage is that I can host 15 people). We will try to do a "hangout on air" using Open Knowledge account (@rgrp can liase with relevant folks to work out to make this happen)

**Comment by loleg** [comment]
I would be happy to organise after next week. There are definitely some
exciting developments to talk about!

**Comment by rgrp** [comment]
@loleg that's fantastic. My suggestion is either a weekend or a weekday evening around e.g. 5pm UK (as that way folks can join from Europe and US).

I've added a checklist of steps above in the issue that we can then walk through.

**Comment by loleg** [comment]
Let's Doodle: https://doodle.com/t5y9k6unr8uhu6mr \cc @rgrp @danfowler @davidmiller @nickstenning @markbrough @mchelen @teleyinex (let me know if you'd really like additional dates / alternate times)

**Comment by danfowler** [comment]
Cool.  I added my preference :)

**Comment by rgrp** [comment]
@loleg i would also ping the list about this kind of thing if you want more responses. Also given timeline maybe worth adding some later dates. General point: I'd pick a late afternoon that works for you and just run with it - most people will make it or not once you have a time.

**Comment by danfowler** [comment]
@loleg sorry, I had to pull out of my chosen timeslot. pick a time, and I will try my best to make it :/

**Comment by mchelen** [comment]
Weekends are best for me, otherwise I can see how well my phone does with
hangouts :)

**Comment by loleg** [comment]
@mchelen @rgrp @danfowler thanks for your date picks. I will be on IRC tomorrow at 4 PM UTC, and we can have a spontaneous Hangout if desired. Since there are few of us who have responded - plus some people are on holiday this week - I've expanded the poll to cover next Thursday and weekend. Apologies for making you do this twice: hopefully there is a day where at least 5 Labs members can join, at which point we can make an announcement on the list, send a few tweets, start a pad as usual.

@davidmiller @nickstenning @markbrough @teleyinex would love to get your picks!

**Comment by rgrp** [comment]
@loleg tomorrow will be too short notice i think for most folks. To be clear the @'s here were just about possible organizers. The important thing is to ping the list and put this on twitter etc and allow at least a week's notice and do the step-by-step instructions. Done efficiently they won't take more than 10-20m but will greatly increase the impact of the call.

**Comment by rgrp** [comment]
Suggestion for agenda in #332 (clarify sysadmin strategy)

**Comment by loleg** [comment]
I have picked **Thursday, April 16, 17:00** (Time zone: London) for the next Labs Hangout instead of continuing to nag on Doodle. If there are any objections, please voice them. 

Rufus has suggested *sysadmin strategy* as a topic, which is definitely a hot topic we should all be aware of. I will also briefly share how I'm trying to increase the impact of our local hackdays (the key words are infrastructure, mentorship, follow-up). Looking forward to hear you soon!

**Comment by danfowler** [comment]
@loleg works for me :)

**Comment by mattfullerton** [comment]
Should work for me too. Good stuff.

**Comment by rgrp** [comment]
@loleg this is great. Are you happy to do the steps at the top of the issue such as pinging the list and getting an etherpad agenda? If you'd like help just flag!

**Comment by loleg** [comment]
@rgrp I've updated the etherpad and having your okays, will ping the list. Wanted to update the site yesterday but got stuck in a git merge.. Everyone, please add your points to http://pad.okfn.org/p/labs-hangouts

**Comment by rgrp** [comment]
@loleg I've tweaked agenda and looks great. Let's start circulating and doing the very checkbox items :-)

**Comment by loleg** [comment]
@rgrp I had a (time) conflict to resolve, will send out invite tonight.

**Comment by loleg** [comment]
Did you all get my invite? First attempt bounced, second got thru. Please
tweet & share & have a great weekend!

**Comment by danfowler** [comment]
Got it :inbox_tray:

**Comment by rgrp** [comment]
@loleg do email labs list with sign up link (etherpad) and tweet :-) Event is now only 2d away :-)

**Comment by loleg** [comment]
I have, last week.. Will repeat and retweet.

**Comment by rgrp** [comment]
yes! i always like the 2-2-2 rule: email 2w, 2d and 2h before the event :-)

**Comment by rgrp** [comment]
@loleg FIXED - though perhaps we want to circulate a follow up email with the notes (or even put up a short blog post with the notes from the meeting).

Also what about booting an issue for the next hangout (in May?)

**Comment by loleg** [comment]
@rgrp I have circulated a mail but a blog post would need more work. I
would rather raise an issue for regular automated hangouts - the next one
is already planned.

**Comment by rgrp** [comment]
@loleg great idea re issue for regular hangouts - plus we probably want to create some step by step by instructions anyone can follow.

**Comment by rgrp** [comment]
@loleg are you going to open an issue for the next hangout (or series). I have to say I think one issue per hangout is sort of nice even if we split out the standard "tasks" somewhere as it makes it easier to track status.

**Comment by loleg** [comment]
@rgrp #345

**Comment by rgrp** [comment]
FIXED :-)
