### ISSUE TITLE
Newsletter Q1 2015

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#322]
Put together a simple newsletter of some of the latest developments.

* [x] Mail the list to ask for announcements
* [x] Quick scan of latest blog posts
* [x] Ping local groups to see if they have any interesting developments (RP?)
* [ ] Post the newsletter
* [ ] Tweet and ping the list!

@loleg @danfowler @davidmiller @markbrough @mchelen @teleyinex @pwalsh - who would be up for being the editor for this edition?

**Comment by pwalsh** [comment]
BTW, Open Australia are using Github to manage the creation of their monthly newsletters: [Repo](https://github.com/openaustralia/newsletter) [Contributing] (https://github.com/openaustralia/newsletter/blob/master/CONTRIBUTING.md) [Example](https://github.com/openaustralia/newsletter/blob/master/editions/2015-02.md)

**Comment by rgrp** [comment]
@pwalsh great suggestion

**Comment by pwalsh** [comment]
I'll edit, and I'd like to follow the pattern used by [Open Australia](https://github.com/openaustralia/newsletter) as linked above.

How do I ping local groups?

**Comment by rgrp** [comment]
there is a slack channel. i think what we really want is a list of "local labs leads" in fact - i know this could be yak-shaving but i may try to recruit that for you now (cc'ing you on the email). Basic idea would be an email alias / list of folks (ultimately we would want them on okfnlabs.org/members - but let's not over-complicate)

**Comment by pwalsh** [comment]
(FYI didn't get the cc)

**Comment by pwalsh** [comment]
@rgrp I'll have some time over coming weekend to do some prep: I thought to:

* hard fork the OA newsletter repo (the acknowledge the idea)
* start collecting ideas there via issues

WDYT for repo: okfn/labs-newsletter

**Comment by rgrp** [comment]
@pwalsh do we need a separate repo - would be nice to keep it as part of this one given that we will post on this site as a blog post etc (or maybe i don't understand the OA newsletter process)

**Comment by pwalsh** [comment]
No need: the flow there is: open an issue with a suggestion for inclusion, then a pull request for the newsletter notifies on the fact of inclusion and closes the issue.

Exact same thing could be done here: possibly using a "newsletter" label to identify as such.

**Comment by rgrp** [comment]
@pwalsh sounds good and forge ahead!

**Comment by pwalsh** [comment]
Created a submission gist here: https://gist.github.com/pwalsh/09a2646bd00cd94e7f51

Can move this into the site later, as a newsletters page or something.

**Comment by rgrp** [comment]
@pwalsh any update here - would be nice to ship ...

**Comment by pwalsh** [comment]
@rgrp yes I let it slip. So, let's aim to publish this Thursday 7th. You think we can still go with the Q1 theme, or too late?

**Comment by rgrp** [comment]
yes, let's go with Q1 and next one will be q2 ;-)

**Comment by pwalsh** [comment]
Draft (ready for publication unless others want to add/edit) is here: https://github.com/okfn/okfn.github.com/pull/346

**Comment by rgrp** [comment]
@pwalsh can we close this as fixed with link to published newsletter?

**Comment by pwalsh** [comment]
fixed: http://okfnlabs.org/blog/2015/05/11/newsletter.html
