### ISSUE TITLE
Get a list of "Local Labs Leads"

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#329]
We want to have a nice list of contact points in all the local Open Knowledge Chapters and Local Groups.

Why?
- So we can get more inter chapter and inter group communication on tech stuff
- Get contributions to the newsletter - see e.g. #322 
- Promote local projects and tools on labs, curate them in the projects list
- Share labs general tools and tech strategy

**Comment by pwalsh** [comment]
Sounds good: I wrote to the au list.

**Comment by mattfullerton** [comment]
I wrote to the German list of CodeForGermany lab leads. If no objections come back, I'll organize a list of all city-leaders.

**Comment by rgrp** [comment]
@mattfullerton sounds great - and are you happy to be the liason or would we email that list direct?

**Comment by loleg** [comment]
Likewise, I have reached out to our community and will start a shortlist.

**Comment by pwalsh** [comment]
Same here with au: reached out and starting a shortlist.

**Comment by mattfullerton** [comment]
@rgrp What exactly were you thinking? It should be no problem to email the list directly - codeforde-lab-leads@lists.okfn.org - my mail to them was more about whether they had anything against being listed as contact points for their cities, and, unsurprisingly, so far no one had anything against it.

**Comment by rgrp** [comment]
@mattfullerton re liason would just be emailing and then passing stuff back or getting folks to add stories directly to the newsletter. Just means that e.g. newsletter does not have to join that list.

**Comment by mattfullerton** [comment]
OK, happy to do that. May need to find someone else in the medium term, as
I'm not actually an OK Lab lead anymore, but still involved...

**Comment by rgrp** [comment]
This is nearly done. My spreadsheet now has 22 contacts for 21 local groups including:

Open Knowledge Egypt
Open Knowledge Bangladesh
Open Knowledge Italy
Open Knowledge Canada
Open Knowledge Russia
Open Knowledge Korea
Open Knowledge El Salvador
Open Knowledge Australia
Open Knowledge Australia
Open Knowledge Japan
Open Knowledge India
Open Knowledge Switzerland
Open Knowledge Ireland
Open Knowledge Ecuador
Open Knowledge Denmark
Open Knowledge Greece
Open Knowledge Deutschland
Open Knowledge Romania
Open Knowledge Spain
Open Knowledge Spain
Open Knowledge Austria
Open Knowledge Bermuda / Bermuda.io

**Comment by rgrp** [comment]
FIXED.

@pwalsh / @loleg we can use this when announcing future newsletters and hangouts.
