### ISSUE TITLE
Project Pages seem to have a column issue

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#330]
At the moment for me on chrome on mac, the RHS column ends up below LHS column rather than beside it. See e.g.

http://okfnlabs.org/projects/nomenklatura/

/cc @danfowler

**Comment by danfowler** [comment]
@rgrp thinking about it, the Recent Project Activity will always show up toward the bottom because it's on a new Bootstrap "row". With the image restored, everything seems to be normal for me across Firefox, Chrome, and Safari (on Mac).

**Comment by rgrp** [comment]
Think this may be an INVALID then. Have to say I'm not sure about activity appearing so far down. Not sure where would be better and that's a different issue.

Closing as INVALID.
