### ISSUE TITLE
Clarify sysadmin strategy

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#332]
In particular, what do we offer and to whom and how do we sustain it?

2 distinct things:

- Experimental space (probably best to get a donated machine if we could)
- Permanent hosting for apps
  - For apps with small data or demand requirement we probably go with heroku or something free if we can
  - For bigger stuff what do we do? Need to research options. One idea is to buy a big machine and then dockerise stuff so we keep things self-contained and we can shut things down.

### Current sysadmin costs

- nomenklatura (heroku): $18 per month (2 basic PG dbs)
- annotateit (heroku): $10 per month (one elasticsearch instance)
- 2 servers on hetzner (one about to go away) ~ $70 a month (i think)

Sysadmin time:

- ...

**Comment by danfowler** [comment]
Yeah, looking forward to talking about this on the call.  Another thing to think about is how to think about what a transition/graduation from "experimental" to "permanent" looks like.  Lots of things probably start out experimental, right?

**Comment by rgrp** [comment]
Started adding info on sysadmin costs

**Comment by rgrp** [comment]
FIXED. https://discuss.okfn.org/t/announcing-shut-down-of-the-labs-server/2437
