### ISSUE TITLE
[newsletter Q2 2015] Core Datasets update

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#333]
Announce: http://okfnlabs.org/blog/2015/01/03/data-curators-wanted-for-core-datasets.html

35+ volunteers and leadership from super contributor @sxren

Most action takes place here https://github.com/datasets/registry/issues with datasets then appearing on http://data.okfn.org/data/

Contributors: @sxren @ekoner @bluechi @san2ho

New core datasets:

* http://data.okfn.org/data/core/media-types (@bluechi and @sxren)
* http://data.okfn.org/data/core/membership-to-copyright-treaties (@bluechi)
* ...

**Comment by pwalsh** [comment]
Added to https://github.com/okfn/okfn.github.com/pull/346

Hopefully we'll publish today. Fee free to comment on the pull request.
