### ISSUE TITLE
[newsletter] New home for the Washington, DC data portal

### ISSUE THREAD

**Issue by emanuelfeld** [okfn/okfn.github.com#334]
Washington, DC's data portal is now accessible on a new platform at http://opendata.dc.gov/. Old datasets are still accessible at http://legacy.data.dc.gov/ while they make the transition.

**Comment by pwalsh** [comment]
HI @emanuelfeld would you mind helping out by writing a short paragraph (3-4 sentences) to summarize the new platform?

**Comment by emanuelfeld** [comment]
@pwalsh how's this?

Washington, DC's data catalog has a new home: http://opendata.dc.gov/. It operates on the ArcGIS Open Data platform and houses data relevant to city services in a variety of formats and with built-in APIs. The service is run out of the DC Office of the Chief Technology Officer, who have been quite responsive to issues and requests. You can give them a shout on Twitter as @opendatadc. Old datasets are still accessible at http://legacy.data.dc.gov/ as they transition to the new site.

**Comment by pwalsh** [comment]
@emanuelfeld that is great. thanks for that.

**Comment by pwalsh** [comment]
Hi @emanuelfeld I've added this to the newsletter. See it here: https://github.com/okfn/okfn.github.com/pull/346

Hopefully we'll publish today. Fee free to comment on the pull request.
