### ISSUE TITLE
Labs Hangout #10

### ISSUE THREAD

**Issue by loleg** [okfn/okfn.github.com#345]
Continuing from where we left off in #320 - it has been suggested that we meet regularly at monthly intervals. 

Next virtual labs meet up: **May 14, 17:00 BST**

<a target="_blank" href="https://www.google.com/calendar/event?action=TEMPLATE&tmeid=NWwwa2s1MHY1azJtaDAwYXRzM3ZjMDYzazQgbGF2cm92c2t5QG0&tmsrc=lavrovsky%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_en-GB.gif"></a>

Sign up and suggestions for topics please via https://pad.okfn.org/p/labs-hangouts

**Comment by rgrp** [comment]
@loleg are you sure this 1700 GMT? Last time it was 1700 BST which is GMT 1600 ...

**Comment by loleg** [comment]
@rgrp fixed, thx. Also calendar link added, pad updated and announce out.

**Comment by rgrp** [comment]
@loleg can we run this as a hangout on air via the Open Knowledge account (that way it ends up in the Open Knowledge youtube channel). I can set this up now and also get you added as a manager of the google plus account so you can manage and do this in future.

**Comment by loleg** [comment]
That's fine, sure.

**Comment by rgrp** [comment]
@loleg I would like to suggest we merge the OpenSpending community hangout into the Labs one as they have both been scheduled at the same time - http://community.openspending.org/2015/05/openspending-community-hangout-revised-date-thursday-14th-may/

All this would mean is a short < 10m slot for Anders Pedersen of NRGI to update re open data and extractives. I think this would be interesting to everyone. does this sound ok?

**Comment by loleg** [comment]
+1, great suggestion.

**Comment by rgrp** [comment]
@loleg do we need to update the etherpad with the new event link and also do we want to update http://okfnlabs.org/events/hangouts/ (i guess we probably want a more automated process for updating that ...)

**Comment by loleg** [comment]
Is there a new event link? We could add an Embed widget
<https://support.google.com/plus/answer/2660854?hl=en> to the page.

**Comment by rgrp** [comment]
@loleg as per https://github.com/okfn/okfn.github.com/issues/345#issuecomment-100465313 here's the event under the Open Knowledge account https://plus.google.com/b/112608652597658788737/events/cvip1l3kgr5uqogjf6r6sk9fcvg

You should have admin access by tomorrow - if not I can run - but we need to update the pad with that and advertise it again to the list and the pad link to twitter.

**Comment by rgrp** [comment]
FIXED. @loleg can we post the link to the hangout on air video (or even embed it!) on http://okfnlabs.org/events/hangouts/

**Comment by rgrp** [comment]
@loleg also can you boot the issue for the next hangout - even if you can't do it i'm sure we can find a volunteer if we ask ...

**Comment by loleg** [comment]
@rgrp the past few days have been rather intense and this week I'm going to
be very hard pressed to make it to the Hangout. would pushing it forward to
next week be an option anyone besides me would appreciate?

**Comment by rgrp** [comment]
Sure - let's do it. Let's push to next week - or even the week after (first week of July) - which is better for me.

**Comment by mattfullerton** [comment]
+1
