### ISSUE TITLE
Transfer annotateit application to me

### ISSUE THREAD

**Issue by nickstenning** [okfn/okfn.github.com#347]
Could you please transfer the Heroku annotateit application to me?

    heroku sharing:transfer -a annotateit nick@whiteink.com

**Comment by rgrp** [comment]
@nickstenning are  you also happy to take responsibility for paying for the ElasticSearch backend etc?

**Comment by nickstenning** [comment]
Yes. `sharing:transfer` will move billing to my account.

**Comment by rgrp** [comment]
Will get on it. Need to add you as a collaborator first it seems.

**Comment by nickstenning** [comment]
`sharing:add EMAIL` then `sharing:transfer EMAIL`.

**Comment by rgrp** [comment]
should be done in next 30m

**Comment by nickstenning** [comment]
I'm really struggling to understand how you've made something so simple so complicated. Could you please transfer me the fucking application that I pretty much exclusively maintain so I can... uh... maintain it?

**Comment by nickstenning** [comment]
For what it's worth, I would probably have been able to hold my tongue if I felt there were even the slightest bit of common sense being applied here.

You removed my access to an application that only I maintain, because I left OKF. You didn't remove access for another administrator that has never worked for OKF.

You insisted that this be managed through an alternate sysadmin procedure, requiring nearly an order of magnitude more time and effort on my part (let alone the part of yourself and your own sysadmin team) to get this sorted.

And now you seem to insist on doing this in tiny dribs and drabs. How in the name of everliving fuck do you have the time to type `heroku sharing:add EMAIL` but not the time to wait half a second until that completes and then type `heroku sharing:transfer EMAIL`?

Sort your shit out, Rufus.

**Comment by rgrp** [comment]
This was done when I said it would be done. I've checked again and re-run the transfer command.

**Comment by nickstenning** [comment]
It wasn't done. It is now. Thank you.

**Comment by rgrp** [comment]
I ran both those commands and only saw your message when I checked back here to close. And then re-ran. I am glad it is now resolved.

**Comment by tfmorris** [comment]
Wow.  Just WOW!  Gives me a whole new perspective on the @hypothesis team, which, until now, I thought had its act together.

@nickstenning You do realize this is a public forum, right?

**Comment by nickstenning** [comment]
I am well aware that this is a public forum. Thanks for your contribution to this issue. We over at Hypothesis have our act together plenty, thank you very much.
