### ISSUE TITLE
Newsletter Q2 / Q3 2015

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#349]
Regular labs newsletter - this time for Q2/Q3 2015.

Please add your suggestions below or as per usual process: http://okfnlabs.org/newsletter.html

@danfowler is acting as editor.

**Comment by pwalsh** [comment]
Submission process is here: http://okfnlabs.org/newsletter.html

I can edit again.

**Comment by flowsta** [comment]
http://okfnlabs.org/newsletter.html doesn't work, 404

**Comment by flowsta** [comment]
We are relaunching http://www.historiasdelgasto.org, I would like to ask about hostings for this and other projects we are involved, can you help us?

**Comment by danfowler** [comment]
@flowsta sounds great! can you try submitting now?

**Comment by flowsta** [comment]
hi @danifowler, what do you mean?

**Comment by danfowler** [comment]
Oh, is information about the relaunch of historiasdelgasto.org and requests for help your newsletter submission.

**Comment by flowsta** [comment]
sure @danfowler I'm going to request for summary to project leader. The project was online with database connection error and the first step was to fix that, now we have to figure out how to relaunch it properly http://www.historiasdegasto.org

**Comment by flowsta** [comment]
@danfowler deadline?

**Comment by danfowler** [comment]
I haven't yet decided when we'll publish the next newsletter, so none yet :smile:

**Comment by danfowler** [comment]
@flowsta I'd like to get this ready by the end of this week.

**Comment by flowsta** [comment]
@danfowler don't worry about it, there is something wrong with the server and they are trying to solve it, it would be better to let it unpublished

**Comment by danfowler** [comment]
Published.
