### ISSUE TITLE
Follow morph.io post - what's happened in the last year?

### ISSUE THREAD

**Issue by mlandauer** [okfn/okfn.github.com#350]
If I was to write a follow up post to http://okfnlabs.org/blog/2014/03/22/morph.html, on what's happened in the last year, all the weird and wonderful things that people are scraping, over 2000 users and over 2000 datasets liberated, etc...

Would this be of interest?

**Comment by rgrp** [comment]
@mlandauer that would be great! Please pull request away!

**Comment by danfowler** [comment]
:+1:

**Comment by rgrp** [comment]
WONTFIX. Have not head anything so closing as part of spring cleaning. @mlandauer if you would like still to do this that would be great and please re-open.
