### ISSUE TITLE
Labs Hangout #11

### ISSUE THREAD

**Issue by loleg** [okfn/okfn.github.com#355]
Continuing from where we left off in #345 - we didn't manage to get to meet in June, so this is a proposal for a July Hangout.

Next virtual labs meet up: **Thursday, July 16, 17:00 BST**

Sign up and suggestions for topics please via https://pad.okfn.org/p/labs-hangouts

**Comment by danfowler** [comment]
Hi, I'll be able to join these again once I'm back in a reasonable timezone next month.

**Comment by rgrp** [comment]
@loleg can i suggest we boot a forum topic for the hangout - https://discuss.okfn.org/c/open-knowledge-labs

Benefit of forum topic is:

- have a nice perma url that is shareable
- markdown support
- people can comment if needed
- you can do things like embed the youtube clip afterwards

Here's an example of how we set it up: https://discuss.okfn.org/t/tech-hangout-june-2015/357 (obviously youtube embed was not there before the call).

**Comment by loleg** [comment]
Good idea, I can set that up on the weekend.

**Comment by loleg** [comment]
Done: https://discuss.okfn.org/t/tech-hangout-july-2015/472

**Comment by rgrp** [comment]
FIXED. This hangout sort of happened (only a few people were able to come). Looking forward to the next one (August or September)
