### ISSUE TITLE
[newsletter] My experience building a 100% Open Source based Open Data platform

### ISSUE THREAD

**Issue by acorbi** [okfn/okfn.github.com#359]
LINK: http://www.open-steps.org/my-experience-building-a-100-open-source-based-open-data-platform/

DESCRIPTION: Alex Corbi shares his experience participating in the development of the www.opendevelopmentmekong.net project, a platform built using 100% Open Source technologies whose aim is to increase transparency in the South Asian countries of the Mekong basin region. The article focuses on its main component; a Knowledge base platform built using CKAN, a great framework initiated by the Open Knowledge and maintained by a great community of developers which makes it the world's leading open-source data portal platform out there. Additionally, Alex gives an overview on how the development was coordinated on Github and the set of additional tools developed around the project, including a plugin to connect Wordpress and CKAN, which can be used and re-purposed for future projects the attendees can find themselves in the future.

**Comment by danfowler** [comment]
Thanks for sharing! We'll get this in to the next newsletter :).

**Comment by danfowler** [comment]
Added.
