### ISSUE TITLE
Open Film Helsinki [newsletter]

### ISSUE THREAD

**Issue by mollycaitlin** [okfn/okfn.github.com#361]
http://www.48dayfilm.com/en/ 

Open culture is in action in Helsinki! An independent production company is making an "open film" called "Night Goes Long" and based on "Le Petit Prince," which went into the public domain this year. It is a feature film being filmed in 48 days. Each stage of production will be totally open and involve audience participation. Audiences have been able to help scout locations around Helsinki by posting to social media, vote for major plot points, participate in an open casting call, access all of the footage (which will be published in the public domain), compete in a crowdsource competition to develop the musical score and the trailer, and comment on the script in drafts as it is developed (all of the drafts published online and open for comment). Pre-production kicks off July 2015, the principal photography starts 8th of August and the film premieres 48 days from that moment in Love & Anarchy film festival in Helsinki. The film will be distributed on TV through Elisa Viihde. Open calls throughout the filming process will be posted on social media from July through September 2015 at #openfilmhelsinki.

**Comment by danfowler** [comment]
Sorry, this wasn't quite within the bounds of the Labs newsletter.  Perhaps you can check out our more general [discussion forum](https://discuss.okfn.org/)?
