### ISSUE TITLE
Suggestions for projects to "feature" for help wanted

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#364]
These should combine:

* Being useful
* Being in state where contribution will be useful (e.g. already partially built)
* A maintainer who can assist contributors
* Having some well-defined (and bite-sized tasks)

Suggestions

* Core Datasets (we probably need a dedicated project page for this ...)
* Frictionless Data tools
* Webshot
* DataPortals
* Froide
* ... 

For a project to be featured on help wanted suggested it **must** have a section called "Help Wanted" with good instructions on its projects page.

**Comment by mattfullerton** [comment]
:+1:

**Comment by danfowler** [comment]
I can trial this out with http://product-open-data.com/

**Comment by rgrp** [comment]
FIXED / DUPLICATE of #422 (Fixed in that we implemented these criteria when doing prioritization).
