### ISSUE TITLE
Make tech contacts we got into a group / badge on discuss.okfn.org

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#366]

**Comment by danfowler** [comment]
Where do tech contacts come from?  Should the group just be called Labs?

**Comment by rgrp** [comment]
@danfowler this is in the spreadsheet we collected of local group tech contacts - remember in #329

**Comment by danfowler** [comment]
Found it.

**Comment by danfowler** [comment]
Done. https://discuss.okfn.org/badges/111/local-labs-coordinators
