### ISSUE TITLE
[newsletter] - Bringing Open Data to the Mobile Platform

### ISSUE THREAD

**Issue by writeosahon** [okfn/okfn.github.com#370]
Hello OKFN.
Below is my submission for the OKFN Labs newsletter.

**Here is a link to the project :** http://odc.utopiasoftwareonline.com/
**Project/App on Google PlayStore:** https://play.google.com/store/apps/details?id=writeosahon.utopiasoftware.odcompanion

**Description:** Open Data Companion (ODC) provides a unified access point to over 120 CKAN open data portals and thousands of datasets from around the world; right from your mobile device. Crafted with mobile-optimised features and design, this is an easy and convenient way to find, access and share open data. ODC provides a framework for all Private Sector, State, Regional, National and Worldwide CKAN open data portals to deliver open data to all mobile users.

**Comment by danfowler** [comment]
Thanks!

**Comment by danfowler** [comment]
Thanks for the contribution.
