### ISSUE TITLE
[newsletter]

### ISSUE THREAD

**Issue by juanortizfreuler** [okfn/okfn.github.com#371]
Title: Supply and Demand of data through Mexico's new Open Data Portal

A link: https://es.scribd.com/doc/274622757/Supply-and-Demand-of-Data-Through-Mexico-s-Open-Data-Portal 

The report, written in non-technical language, provides the reader with contextual data to understand the challenges the government of a developing country is facing in the implementation of an Open Data Portal. The report includes análisis of availability and quality of key datasets, critical analysis of the existing normative framework, an analysis of web traffic towards the portal, as well as insights from interviews with over two dozen professional Mexican data users. 
The report was produced following the standards of Open Research.

![grafico-circulos 1](https://cloud.githubusercontent.com/assets/14280123/9857467/9edcb930-5b12-11e5-8d2d-6cb89b3dd710.png)

**Comment by danfowler** [comment]
Excellent!  Thanks for the contribution!
