### ISSUE TITLE
Specify front-matter defaults to simplify metadata

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#373]
By setting some proper front matter defaults in _config.yml, the needed metadata for a blog post or project post can be cut down somewhat.  E.g. layouts can be set for all blog posts or project posts at once.

https://jekyllrb.com/docs/configuration/#front-matter-defaults

**Comment by rgrp** [comment]
@davbre would you be up for doing this one?

**Comment by danfowler** [comment]
Thanks @davbre ! Closing out! :+1: :+1:
