### ISSUE TITLE
[newsletter] Agate, the Python data analysis library for humans, has reached version 1.0

### ISSUE THREAD

**Issue by onyxfish** [okfn/okfn.github.com#377]
"agate is a Python data analysis library that is optimized for humans instead of machines. It is an alternative to numpy and pandas that helps you solve real-world problems with readable code."

http://agate.readthedocs.org/

(someone suggested I submit this a while back, but I've only just reached 1.0, so I'm doing it now.)

**Comment by danfowler** [comment]
@onyxfish Looks excellent!  Will definitely get this in.  Interested in writing a post to announce 1.0?  :wink:

**Comment by onyxfish** [comment]
@danfowler Thanks! I'm already writing an announcement post for the folks at Source. I'd be happy to blurb and cross-link or something if you're interested.

**Comment by danfowler** [comment]
@onyxfish excellent! do give a ping :smile:

**Comment by onyxfish** [comment]
@danfowler Here's the link! https://source.opennews.org/en-US/articles/introducing-agate/ Let me know if there is anything else you need!

**Comment by danfowler** [comment]
@onyxfish :+1:
