### ISSUE TITLE
[newsletter] Mira, simple HTTP APIs for your CSV files

### ISSUE THREAD

**Issue by davbre** [okfn/okfn.github.com#382]
[https://github.com/davbre/mira](https://github.com/davbre/mira)

This is a small application developed using Ruby-on-Rails. You upload a datapackage.json file to it along with the corresponding CSV files and it gives you a read-only HTTP API. It's pretty simple - it uses the metadata in the datapackage.json file to import each CSV file into its own database table. Once imported, various API endpoints become available for metadata and data. You can perform simple queries on the data, controlling the ordering, paging and variable selection. It also talks to the DataTables jQuery plug-in.

**Comment by danfowler** [comment]
Thanks for your submission! Will definitely get this in. :smile:

**Comment by danfowler** [comment]
@davbre looking at this again, three things come to mind:

- Would you actually be interested in also listing this as a project (http://okfnlabs.org/projects/add) and maybe even writing a short blog post (http://okfnlabs.org/blog/add/) on our site?  
- I noticed that you work in the pharmaceutical industry and that some of your examples for mira used clinical trial data.  Are you familiar with the Open Knowledge project [Open Trials](http://opentrials.net/)?
- Are you interested in getting involved more deeply with Labs?  https://github.com/okfn/okfn.github.com/issues/367

**Comment by davbre** [comment]
@danfowler

Sure, I'll add the project, perhaps over the weekend. When I find some time
I might add a blog post. Regarding Open Trials, thanks for the link. I was
vaguely familiar with it - it looks like it's worth a revisit ;) As for
getting involved, yes I suppose I could in some small capacity or other. I
saw somewhere that you lot organise hangouts. I could participate in one of
those, and we can discuss further if you like.

**Comment by rgrp** [comment]
@davbre this is *awesome* :-)
