### ISSUE TITLE
Reboot datapatterns

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#390]
See issue here: https://github.com/okfn/datapatterns/issues/73 and https://github.com/okfn/ideas/issues/76

@todrobbins @seralf what do you think of the current state of http://datapatterns.org/.  Are either of you interested in being a maintainer?

Once we're satisfied, we can [add as a Labs project](http://okfnlabs.org/projects/add/) :).

**Comment by todrobbins** [comment]
I'm interested in maintaining. Currently, I'm a bit overwhelmed, but am willing to work with anyone (including @seralf) to keep the project alive.

**Comment by seralf** [comment]
I can contribute if needed, even if I'm not the faster contributor at the
moment, certainly :-)

2015-12-01 17:54 GMT+01:00 Tod Robbins <notifications@github.com>:

**Comment by danfowler** [comment]
@todrobbins @seralf thanks guys, I totally understand. I pushed it along a bit.  I think the biggest thing that needs doing is just a little bit of file [restructuring](https://github.com/okfn/datapatterns/issues/79).

**Comment by todrobbins** [comment]
I'll get on that ASAP.

**Comment by todrobbins** [comment]
@danfowler can you add me as a team member?

**Comment by todrobbins** [comment]
Thanks for the add @danfowler!

**Comment by danfowler** [comment]
:sunglasses:

**Comment by rgrp** [comment]
@todrobbins how are you doing here - this is a great project and we are now super close to having this fully operational again ;-)

**Comment by todrobbins** [comment]
I was going to make a bad Star Wars joke, but I'll refrain. I need to make one more review of the current code, but I think we're very close aside from reorganizing some of the articles/menu hierarchy.

**Comment by rgrp** [comment]
@todrobbins brilliant - i also think we probably want to cut and/or move http://datapatterns.org/pattern/ stuff to front page and probably make the front page super simple (keep the general layout but maybe just add the list of patterns or some about text directly into the front page)

**Comment by rgrp** [comment]
@todrobbins how's it going? Super excited to see this updated.

**Comment by seralf** [comment]
let me know if you need some help!
I have less time, but still I can contribute a little, if needed
:-)

2016-01-04 18:30 GMT+01:00 Rufus Pollock <notifications@github.com>:

**Comment by rgrp** [comment]
@seralf we'd love your help - as you know there are a bunch of open issues e.g. https://github.com/okfn/datapatterns/issues/79

**Comment by rgrp** [comment]
FIXED. I'm going to closed this as fixed as site is back up even if other stuff not sorted.
