### ISSUE TITLE
[newsletter] Renewed activity in the Datasets registry

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#391]
Thanks to @pdehaye, the new core datasets managing curator :).

https://github.com/datasets/registry/issues

**Comment by pdehaye** [comment]
I am hoping I can flag some good examples that are ready to package and "easy", by the time of the newsletter, and can help onboard some people that way. First up: Big Mac index.

**Comment by danfowler** [comment]
@pdehaye Excellent :+1:

**Comment by todrobbins** [comment]
Nice work @pdehaye!
