### ISSUE TITLE
Create a design "project" where we store info about our design approach and assets

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#392]
Suggest creating https://github.com/okfn/design (or similar) deploying to gh-pages at http://okfnlabs.org/design/

This is the place to go to find out about:

* Style guides
* Generic themes for:
  * jekyll e.g. https://github.com/okfn/handbook-theme
  * wordpress
  * ... 
* Key design assets

...

**Comment by todrobbins** [comment]
:+1: a pattern library/style guide would be great. See also: https://github.com/davidhund/styleguide-generators#user-content-jekyll

**Comment by danfowler** [comment]
:+1:

**Comment by rgrp** [comment]
We now have https://github.com/okfn/ok-media - could this go there?

**Comment by rgrp** [comment]
FIXED - we can use https://github.com/okfn/ok-media

DUPLICATE in terms of adding info for new issue https://github.com/okfn/ok-media/issues/6
