### ISSUE TITLE
Move blog.datahub.io content to forum

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#404]
There are very few but important posts on http://blog.datahub.io.  All posts should live as their own "sticky" topics here: https://discuss.okfn.org/c/open-knowledge-labs/datahub/

See: https://github.com/okfn/okfn.github.com/issues/389#issuecomment-169974415

**Comment by 42piratas** [comment]
Hi, there! Although this is open, it seems the blog is down. 
Is the task still open? Thanks!

**Comment by rufuspollock** [comment]
OBSOLETE. no longer relevant. new datahub.io blog is at https://datahub.io/blog/
