### ISSUE TITLE
[pm] Sprint 15 February - 28 February

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#405]
The purpose of this meta-issue is to define an initial two week sprint to take on and complete some Labs tasks within that sprint.  In this initial sprint, I will probably take on the majority of tasks, but hopefully, in the next sprint, we can have others take on some commitments.  This is loosely inspired by IPFS's [project management](https://github.com/ipfs/pm) strategy.  As we go along, this workflow will certainly change :sweat_smile:.

| Task | Lead | Estimate (days) | Issue | Done | 
|----|----|----|----|----|
| Sync with Labs leads |  | 0.25 | |  |
| Schedule February Hangout | @danfowler | 0.25 | https://github.com/okfn/okfn.github.com/issues/386 | :heavy_check_mark: |
| Finalize a vision/manifesto document | @rgrp | 0.5 | #409  |  |
| Recategorize projects as per plan into active, retired | @davbre + @rgrp  | 0.5 | https://github.com/okfn/okfn.github.com/issues/274 | :heavy_check_mark:  |
| Establish "priority" projects | @rgrp | 0.5 | https://github.com/okfn/okfn.github.com/issues/402 | :heavy_check_mark: |
| Solicit submissions for & create Q12016 Newsletter | @jwieder | | https://github.com/okfn/okfn.github.com/issues/398 | |

What do you think of this methodology Labs team?  Are any of you interested in taking on any tasks?

@davbre
@davidmiller 
@jgkim 
@loleg
@mattfullerton 
@pdehaye
@jwieder 
@todrobbins

**Comment by davbre** [comment]
@danfowler - this approach looks fine to me. I could give a hand with issue
#274.

**Comment by todrobbins** [comment]
Looks great @danfowler! A what a helpful table! Markdown FTW! Do you want us to edit your comment to add table rows?

**Comment by davidmiller** [comment]
@danfowler Is there a draft of the vision/manifesto doc? Happy to take a look when there is. 

Semi-related: #401 links to a mailing list discussion about a chat space - did that ever get decided on/actioned?

**Comment by puppycidedb** [comment]
@danfowler I also think this approach is good. I would be willing to
take on a task - I don't have a preference, so if something is left over
I can tackle it.

**Comment by danfowler** [comment]
OK, picking this up again and adjusting dates.  I've scheduled the next hangout planned, and I really hope you all can join.

https://discuss.okfn.org/t/tech-hangout-february-2016/2019

@davbre can you take a look at #274 ? 
@todrobbins feel free to edit the table :)
@davidmiller nothing was decided. Do you have a strong preference?
@puppycidedb can you help solicit suggestions for a new newsletter and add that task the list?

**Comment by puppycidedb** [comment]
@danfowler - I will be available for the tech hangout next week & I will
get started on the newsletter tasks. - @jwieder / @puppycidedb

**Comment by davbre** [comment]
@danfowler - yes, that's fine - I'll take a look when I can.

**Comment by jwieder** [comment]
@danfowler Updated the table above, created a blog post requesting submissions ( [Pull request #406](https://github.com/okfn/okfn.github.com/pull/406) ), sent out a tweet to okfnlab followers & added a [discussion list topic](https://discuss.okfn.org/t/topics-needed-for-2016q1-newsletter/2024)

**Comment by danfowler** [comment]
@jwieder :+1: :+1:

**Comment by davidmiller** [comment]
@danfowler I have no strong opinions, just wondering what the status was. It's the kind of thing where making a decision is more important than the value of the decision.

I delegate any vote I might have had to you ;)

**Comment by rgrp** [comment]
@danfowler - i missed this originally (do feel free to @ me in future!). Looks **really** good.

@davidmiller +1 on the value of the decision. As for that forum thread I have just commented this weekend with an update recommending (personally) gitter. I have created the public room here https://gitter.im/okfn/chat and invite folks to join and try it out.

@davidmiller The [manifesto / vision doc is here][doc]. If you were up to taking at look at this this is something I'd love to work with you on.

[doc]: https://docs.google.com/a/okfn.org/document/d/1vZQaEQ6Rm8eFk54XBN9KhBGQE1KomesFJg3kRalO4AU/edit?usp=drive_web

**Comment by jwieder** [comment]
@danfowler Hi Dan - I'd like to join today's hangout but I can't find the event link on Twitter or the discussion page. Do you have the link available?

**Comment by rgrp** [comment]
@danfowler how are we doing here - do you have any updates on the (beautiful) tasks matrix :-)

@davidmiller let me know yay or nay on doing a session on the manifesto / vision doc.

**Comment by rgrp** [comment]
@danfowler i've updated tasks matrix with two assignments on items. Do you know who is taking on updating labs leads? Could we get a separate issue for this as i have some suggestions to offer.

**Comment by danfowler** [comment]
@rgrp thanks. I will take on updating team leads.

**Comment by pwalsh** [comment]
@danfowler a lot going on here, great! Can you please also communicate this stuff internally at OKI, especially with the Tech Team.

**Comment by rgrp** [comment]
@danfowler how are we doing here with the newsletter and the syncing with labs leads? Everything else is done :birthday:

**Comment by rgrp** [comment]
@danfowler can we close this out and move items to 2016 Q2 item.

**Comment by danfowler** [comment]
Closing.
