### ISSUE TITLE
Update contact page 

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#415]
http://okfnlabs.org/contact/

- [ ] Link to new chat space(s)
- [ ] Remove email? (for private comms use direct messaging in Discourse)

**Comment by rgrp** [comment]
:+1: and suggest we do this asap :smile: (e.g. next sprint)

**Comment by rgrp** [comment]
@danfowler bump! Or do you want someone else to take this on?

**Comment by rgrp** [comment]
@davbre would you be up for taking this on - super simple :smile: 

* The new new chat space is https://gitter.im/okfn/chat
* We should remove the private email and point people to https://discuss.okfn.org/c/open-knowledge-labs

**Comment by davbre** [comment]
@rgrp yes, I'll update that. Do you want to keep the section pointing to the IRC channel?

**Comment by danfowler** [comment]
@davbre :+1: Thanks. I'd say remove the pointer to the IRC channel as well as the "Announce List and Newsletter".  Keep the general Mailing List.

**Comment by davbre** [comment]
@danfowler the signup to the announce list and newsletter appears on the
homepage as well. Remove that also I guess?

**Comment by danfowler** [comment]
Yes.  I may re-add in the future, but it's going unused now.

**Comment by rgrp** [comment]
FIXED in #428 thanks to @davbre
