### ISSUE TITLE
Update projects listing page (using priority etc)

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#422]
### Projects listing page (/projects/)

We need to update projects page to reflect new priority. Initial thoughts:
- Priority projects at top by default.
- Featured projects somewhere (how much duplication is there with priority?)
- If you search you just get search results

_Derived from and subissue of #274_
### Projects Add page (/projects/add)
- [ ] On projects add page add the enumerations we have created and their explanations from the [spreadsheet](https://docs.google.com/spreadsheets/d/1CiVqAeKqj_U57bDBW1Jz95WN6dS39Rup-hvqvDj2idE/edit#gid=1083660843)
### User stories

As a New Visitor who is interested in contributing to projects I want to see the priority projects where I can contribute

As a Browsing Visitor (not planning to contribute) I want to know what kinds of projects you do and what stage they are at so that ... (??)

As a Labs Member I want to browse our entire archive of labs projects so that ...

As a Labs Member I want to add or updatea  project so that the list on the website is up to date and useful to others

**Comment by rgrp** [comment]
@davbre any thoughts here? /cc @danfowler

**Comment by davbre** [comment]
@rgrp I think the introduction of the priority attribute may be separating
foundation/okfn projects and what you might call community projects. Might
be worth considering labeling this way?

The site uses the isotope js library for this page. One option might be to
add more obvious filters in the form of buttons for say "Featured",
"Foundation", " Community", "Priority" or whatever. See some examples at
http://isotope.metafizzy.co/filtering.html. I'll tinker around with it when
I get a chance

**Comment by rgrp** [comment]
@davbre the intention of priority was not to discriminate OKI vs non OKI projects - the basis of distinction was explained in the spreadsheet - though many priority projects may have OKI has lead maintainers at present primarily because size and clear owner were criteria.

So, in general, i think i would want to stick with "priority" as the criteria and leave other things to filter into that.

Right now I think we could keep it really simple and just replace feature with priority as default search option and come back to later improvements.

**Comment by davbre** [comment]
@rgrp I wasn't suggesting the intention was to discriminate between OKI vs
non-OKI projects. I was just pointing out that there seems to be two types.
And that's fine, I'll change the default filter.

**Comment by rgrp** [comment]
@davbre got you. I got you and feedback is very useful. Let's get #274 closed and then we'll move on this one.

**Comment by rgrp** [comment]
@davbre would you be up for starting on some of this.

As a first step, what about updating the projects/add page with the enumerations and their explanations.

**Comment by rgrp** [comment]
@davbre wondering if you would be up for this.  Immediate priorities:

* Update `projects/add` with info about our concepts
* Update `projects` to show priority by default ...

**Comment by rgrp** [comment]
@davbre pinging again ;-) - if you had a moment here it would be awesome and we could finally close!

**Comment by davbre** [comment]
@rgrp - the `projects` page is currently showing the priority projects by default and the `projects/add` was also updated some months back. Is there something else needed as well?

**Comment by rgrp** [comment]
@davbre ah perfect 👍  😄  I'm going to close this then!

**Comment by rgrp** [comment]
FIXED. See previous comment.
