### ISSUE TITLE
Further clean up of projects list (March 2016)

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#424]
We are bulk editing projects csv in [this google doc][gdoc]. See second line for additional comments:

* [x] Add other OK projects e.g. CKAN etc (lines 48-58 in spreadsheet and bolded)
* [x] Change OKFN as owner/author to Open Knowledge International (or "Open Knowledge Intl" if we need it short) - may need to create a user for this ...
* [x] Implement category - TODO: agree on final designations before we do so
* [ ] Implement theme - TODO: ditto
* [x] `author / maintainers / contributors`: we have too many options. I think we want to simplify. Probably a separate issue.
  * `author` should also be a labs username and is probably better called `owner` (??)
* [x] Delete `tags`
* [x] `permalink` and `slug`: can we delete now?

[gdoc]: https://docs.google.com/spreadsheets/d/1CiVqAeKqj_U57bDBW1Jz95WN6dS39Rup-hvqvDj2idE/edit#gid=1632238835

**Comment by rgrp** [comment]
Change of OKFN to OKI happened in https://github.com/okfn/okfn.github.com/commit/5cf1c6a095053e31a5da870b0dd62ae1a6085077

**Comment by rgrp** [comment]
@davbre any thoughts here on what we should do (before we then do it ...)

**Comment by davbre** [comment]
@rgrp Some of the above have already been implemented. "category" is in place as a filter (and reflects what is currently in the google docs spreadsheet). This can be easily be changed by just editing the corresponding column in the projects csv file. Also, `permalink` and `slug` have already been deleted.

I don't know what "implement theme" is referring to. Could you elaborate?

Regarding `authors`, `maintainers`, `contributors`, I'm not sure yet. If `author` is replaced by `owner`, then I guess `maintainers` could be dropped leaving `owner` and `contributors` (where `contributors` would be a merge of what is currently in `maintainers` and `contributors`). Or are you thinking along the lines of just having `owner`?

**Comment by rgrp** [comment]
@davbre - i agree. Replace `author` with `owner` and merge `contributors` and `maintainers` into `contributors`.

Re `theme` i mean the idea of classifying projects under specific themes. I think we leave this for now.

**Comment by danfowler** [comment]
This looks closed to me.  Only as of #450.  Only remaining issue is project theme, but we need to define clearly first.
