### ISSUE TITLE
Homepage blog post username links

### ISSUE THREAD

**Issue by davbre** [okfn/okfn.github.com#431]
On the homepage we display blog post titles along with the corresponding author name, date, and a teaser. The author's name is not linked to that user's profile. Should it be? (Note that if you click into the actual blog post the author's name is linked.)

**Comment by danfowler** [comment]
My feeling no.  I think it's more valuable for people to click through to the post.

**Comment by davbre** [comment]
@danfowler - that's fair enough. I'll close this out.
