### ISSUE TITLE
Update /events/

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#434]
Kind of busy and hard to read as it is essentially two large, mostly irrelevant embeds.  Suggest it describes the two types of events we typically run:

- Open Knowledge Labs Online Hangouts (virtual)
- Open Data Maker (in-person)

- [x] I'm not sure we need attendance form if we use attending.io
- [x] Timemap is still cool, but maybe it needs to go somewhere else

**Comment by rgrp** [comment]
@danfowler +1 on all of this.

* Timemapper is out of date and can be removed (maybe put it at the bottom of Open Data Maker page - http://okfnlabs.org/events/open-data-maker/ - so we have an archive)
* Attendance form was for internal use and was just there for a quick link. Could be dropped.
* Embedding the massive empty calendar is perhaps not needed (or maybe we should put it in agenda form).
* We can make this page really simple - just state that we run it at this regular time and they get posted in the forum and link to the forum section or similar.

**Comment by rgrp** [comment]
@danfowler also want to suggest we merge http://okfnlabs.org/events/hangouts/ into the main events page and put that content under a part of the page called e.g. "Archive"

**Comment by danfowler** [comment]
OK, merging everything into /events/ and adding the timemap to /events/timemap/.
