### ISSUE TITLE
Update GitHub activity include

### ISSUE THREAD

**Issue by danfowler** [okfn/okfn.github.com#439]
[GitHub activity include](https://github.com/okfn/okfn.github.com/blob/master/_includes/activity.html) should reflect featured or otherwise high priority projects.

Suggest getting project information from something like:

`{{ site.data.projects | where: "featured","TRUE" | jsonify }};` 

and filtering.

**Comment by rgrp** [comment]
@danfowler great suggestion.

@davbre would you like to implement 😄  ?

**Comment by rgrp** [comment]
FIXED. in https://github.com/okfn/okfn.github.com/pull/440
