### ISSUE TITLE
[pm] Sprint 9 May - 23 May

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#442]
| Task | Lead | Estimate (days) | Issue | Done |
|----|----|----|----|----|
| Task 1 | Lead by | half day | Issue | :heavy_check_mark: |
| Labs Hangout | @danfowler  | 0.25 | yet to open | :heavy_check_mark: |
| Handbook Sprint | @gsilvapt | 14 days | https://github.com/okfn/handbook/issues/99 | | 
| Further clean up of projects list (March 2016) | @davbre | ? | #424 | :heavy_check_mark: |

**Comment by rgrp** [comment]
@danfowler @gsilvapt @davbre any thoughts on other items to include.

@gsilvapt it would also be nice to turn this list into a table as per table in description #405 if you were up for trying.

**Comment by gsilvapt** [comment]
@rgrp This?

| Task | Lead | Estimate (days) | Issue | Done |
|----|----|----|----|----|
| Task 1 | Lead by | half day | Imaginary Issue | :heavy_check_mark: |

**Comment by rgrp** [comment]
@gsilvapt perfect - i've tweaked a bit.

**Comment by gsilvapt** [comment]
Did a small change to add the actual sprint issue I just created.

**Comment by danfowler** [comment]
@rgrp no issue to open for Labs Hangout. "Issue" will always be a new post on the forum: https://discuss.okfn.org/t/labs-hangout-may-2016/2593

**Comment by rgrp** [comment]
@danfowler great and we can just link to that rather than an issue.

@danfowler can you boot an item for a new sprint?

**Comment by danfowler** [comment]
And now this sprint has ended.

![game-of-thrones-jon-snow-my-watch-has-ended](https://cloud.githubusercontent.com/assets/772616/17638147/312bf7fc-60b6-11e6-9cc1-9cd4fea61225.jpg)
