### ISSUE TITLE
Timemapper not working?

### ISSUE THREAD

**Issue by ebeshero** [okfn/okfn.github.com#505]
Timemapper appears not to be working at all: 
See http://timemapper.okfnlabs.org/ which is generating an application error. I have a series of timemapper timelines that aren't serving to my students as a result--is this something easy to fix?

**Comment by todrobbins** [comment]
@ebeshero it looks like it might be a Heroku issue. Paging @danfowler.

**Comment by rufuspollock** [comment]
@todrobbins @danfowler is no longer available for this. But I can help debug or someone else at OKi 😄

**Comment by brew** [comment]
@ebeshero Thanks for the report. timemapper should now be back online.

**Comment by rufuspollock** [comment]
@brew could you detail what happened?

**Comment by brew** [comment]
Sure - the issue wasn't really technical, but administrative. We had run our of hours on our hosting plan, and needed to upgrade it for timemapper.
