### ISSUE TITLE
https wildcard certificate

### ISSUE THREAD

**Issue by andylolz** [okfn/okfn.github.com#521]
Hello! We received a request for https support on http://datapipes.okfnlabs.org (okfn/datapipes#127).

It would be cool! I guess it would require a wildcard certificate on the okfnlabs.org domain. Is that doable?

Thanks!

**Comment by tfmorris** [comment]
Let's Encrypt gives out free wildcard SSL certs

https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by andylolz** [comment]
Thanks, @tfmorris!

I’ve realised I should be able to do this myself for datapipes, using ACM on heroku (which does indeed use Let’s Encrypt!)

Closing this one.
