### ISSUE TITLE
Automated Certificate Management has failed for your app datacatalogs-org

### ISSUE THREAD

**Issue by mattfullerton** [okfn/okfn.github.com#524]
Automated Certificate Management has failed for the following domains:

datacatalogs.org | CDN not returning HTTP challenge
dataportals.org | CDN not returning HTTP challenge
new.datacatalogs.org | Unable to resolve DNS for new.datacatalogs.org
www.datacatalogs.org | Unable to resolve DNS for www.datacatalogs.org

**Comment by roll** [comment]
I hope it will help (pls let me know if we need other tweaks at CloudFlare level).

Closing for now. Please re-open if needed.
