### ISSUE TITLE
timemaps won't load

### ISSUE THREAD

**Issue by kasplin** [okfn/okfn.github.com#546]
I read the previous thread #545 about timemapper at http://timemapper.okfnlabs.org/ that was happening in September, and seems to be happening again. I can see, edit, and use my old timemaps, but any new ones have a perpetual loading screen (3 days and counting).  I thought it might have to do with the increased number of options for how to publish your google sheets, but none of the possible publishing options helped.  Is it something on the back end, as it was in September?  Can it be fixed?

**Comment by kasplin** [comment]
@amercader You seemed to be able to fix this in September.  Is there a similar problem now?

**Comment by Schimy** [comment]
hi, I got the same problems ... please fix them soon!

thx a lot!

**Comment by amercader** [comment]
We are assessing options for timemapper. Please check this issue for updates https://github.com/okfn/timemapper/issues/224
