### ISSUE TITLE
TimeMapper without Twitter?

### ISSUE THREAD

**Issue by haggis78** [okfn/okfn.github.com#552]
In light of the chaos at Twitter, we can't take it for granted that everyone has or wants to have an account there. What prospects are there for a way to sign in to TimeMapper that are independent of Twitter? Thank you.

**Comment by aivuk** [comment]
@haggis78 I think it is better to move this discussion to timemapper repository https://github.com/okfn/timemapper/. I agree with you that it would be a good idea to add other sign in option to timemapper and it wouldn't be so hard considering that it is using passport library that supports a lot of different options as you can see here https://www.passportjs.org/packages/. The biggest work would be just to change the current login button that redirects the user directly to Twitter to open a dialog where they could choose which user auth provider to use.

**Comment by haggis78** [comment]
@aivuk Thank you. I have reposted the Issue where you suggested.
