### ISSUE TITLE
datahub.io ssl certificate issue

### ISSUE THREAD

**Issue by g-marius** [okfn/okfn.github.com#553]
Hi team,

[okfn contact](https://okfnlabs.org/contact/) suggests this method for reaching out.

Looks like datahub.io is not accessible, trying to open https://datahub.io/  returns
```
datahub.io uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**Comment by rufuspollock** [comment]
@g-marius this is fixed. thank-you for flagging. PS best place to post re datahub is https://github.com/datopian/datahub-v2-qa
