### ISSUE TITLE
Add publicbodies project to projects list

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#63]
* http://publicbodies.org/
* github: https://github.com/okfn/publicbodies
* Contributors include: rgrp, wombleton, pudo, rossjones, dread ...
* Posts
  * http://okfnlabs.org/blog/2013/05/01/publicbodies.org-an-update.html
  * http://pudo.org/blog/2011/10/24/publicbodies.html

@andylolz this could be a good tryout for our walk-through of new add projects setup (this is also a great project for contributors ...)

**Comment by rgrp** [comment]
@danfowler up for doing this one too?

BTW: I think this is one to mark as featured and to mark as good for contributors.

**Comment by danfowler** [comment]
![publicbodies](https://cloud.githubusercontent.com/assets/772616/5678521/78916810-9804-11e4-9054-8db52c6b2208.png)
