### ISSUE TITLE
Better join in process

### ISSUE THREAD

**Issue by rgrp** [okfn/okfn.github.com#68]
Discussion issue about how to further improve the join in process  - http://okfnlabs.org/join/ etc

Related issues

* cf better projects page #46 
* cf integrate ideas into website #50

**Comment by danfowler** [comment]
This page is largely a wall of text.  Perhaps some pleasant images could encourage more people to join.  

Code4SA has a nice call-to-action of [active GitHub issues](http://code4sa.org/#github-issues) right on their front page.

**Comment by rgrp** [comment]
@danfowler great suggestions. Do you want to take this on?

**Comment by rgrp** [comment]
WONTFIX / FIXED. Large parts of this are done and no clear action remaining.
